#!/usr/bin/env bash
# AUTO-GENERATED by scripts/generate-skill-hooks.sh — do not edit manually
# Generated: 2026-02-22T00:00:00Z
#
# To regenerate from SKILL.md frontmatter:
#   bash scripts/generate-skill-hooks.sh
# Then hand-tune the regex patterns as needed.

declare -A SKILL_PATTERNS
declare -A SKILL_TIERS

# --- Tier 1: Methodology (process/approach skills) ---

SKILL_PATTERNS[planning]='plan.*(feature|task|sprint|this|implement|approach|phase|change|refactor|migration)|break.?down.*(feature|task)|implementation.?plan|(create|make|need|start|write|draft|let.?s).*plan'
SKILL_TIERS[planning]=1

SKILL_PATTERNS[debugging]='debug|fix.*(bug|this)|why.*(fail|broken)|troubleshoot|stack.?trace|broken.?test|test.*broken|flaky.?test|regression|unexpected.?behav'
SKILL_TIERS[debugging]=1

SKILL_PATTERNS[code-review]='review.*(code|\bprs?\b|diff|merge)|code.?review|audit.*code|critiqu'
SKILL_TIERS[code-review]=1

SKILL_PATTERNS[simplifying-code]='simplif.*code|clean.?up.*code|polish.*code|\brefactor\b|declutter|reduce.?complexity|remove.*(dead.?code|ai.?slop)|improve.?readability'
SKILL_TIERS[simplifying-code]=1

SKILL_PATTERNS[brainstorming]='brainstorm|help.?me.?think|what.?should.?we.?build|explore.*approach'
SKILL_TIERS[brainstorming]=1

SKILL_PATTERNS[verification-before-completion]='verif.*(complet|done|pass|success)|completion.?claim|fresh.?evidence|verify.?before.{0,12}(commit|push|pr|merge)'
SKILL_TIERS[verification-before-completion]=1

SKILL_PATTERNS[receiving-code-review]='receiv.*(review|feedback)|pr.?feedback|implement.*(suggestion|feedback)|push.?back.*review|address.*(review|feedback)'
SKILL_TIERS[receiving-code-review]=1

SKILL_PATTERNS[writing-tests]='writ.{0,25}(test|spec)|add.?test|test.?quality|test.?anti.?pattern|mock.*(bad|wrong|instead)|test.?discipline'
SKILL_TIERS[writing-tests]=1


# --- Tier 2: Domain/Language (language/framework-specific) ---

SKILL_PATTERNS[php-laravel]='laravel|eloquent|\bblade\b|\bartisan\b|phpunit|phpstan|composer\.(json|lock)|\bphp\b.{0,20}(controller|model|service|middleware|migration|queue|job|route|facade|factory|seeder)|feature.?test.*\.php|unit.?test.*\.php|test.*(controller|model|service|action|job|command|endpoint).*\.php'
SKILL_TIERS[php-laravel]=2

SKILL_PATTERNS[react-frontend]='\breact\b|next\.?js|react.*test|jsx|tsx|\bhook[s]?\b.*component|vitest|component.?test|hook.?test|\brtl\b|testing.?library|snapshot.?test'
SKILL_TIERS[react-frontend]=2

SKILL_PATTERNS[nodejs-backend]='\bexpress\b.*server|\bfastify\b|node\.?js.*(backend|server|api)|server.?side.?typescript'
SKILL_TIERS[nodejs-backend]=2

SKILL_PATTERNS[python-services]='\bfastapi\b|python.*(cli|service|backend|api)|async.*python|\bruff\b'
SKILL_TIERS[python-services]=2

SKILL_PATTERNS[postgresql]='postgres|jsonb|row.?level.?security|\brls\b|\bcte[s]?\b|window.?function|explain.?analyze|partition.*(table|range|list|hash)|connection.?pool.*(pg|postgres|bouncer)|upsert|full.?text.?search|tsvector'
SKILL_TIERS[postgresql]=2

SKILL_PATTERNS[terraform]='terraform|opentofu|\biac\b|infrastructure.?as.?code|\bhcl\b|tfvars|tftest'
SKILL_TIERS[terraform]=2

SKILL_PATTERNS[linux-bash-scripting]='bash.?script|shell.?script|linux.?automation|system.?script|cron.?job|deployment.?script'
SKILL_TIERS[linux-bash-scripting]=2

SKILL_PATTERNS[pinescript]='pine.?script|tradingview|backtest'
SKILL_TIERS[pinescript]=2

SKILL_PATTERNS[frontend-design]='frontend.*(design|interface)|ui.*(design|build|create)|build.*(web.?component|web.?page|landing.?page|dashboard)'
SKILL_TIERS[frontend-design]=2

SKILL_PATTERNS[tailwind-css]='tailwind|@theme.*token|@utility.*css|tailwind.?variant|class.?variance|\bcva\b|\btv\(\b|utility.?class.*css|dark.?mode.*css'
SKILL_TIERS[tailwind-css]=2

SKILL_PATTERNS[agent-native-architecture]='autonomous.?agent|mcp.?tool|self.?modif|agent.?native|prompt.?native'
SKILL_TIERS[agent-native-architecture]=2

# --- Tier 3: Supporting/Workflow ---

SKILL_PATTERNS[writing]='\brewrite\b|humanize|improve.*text|fix.*(tone|wording)|proofread|remove.*ai.?language|\bpr.?description\b|write.*(pull.?request|\bplan\b)'
SKILL_TIERS[writing]=3

SKILL_PATTERNS[md-docs]='update.*readme|update.*agents|init.*agents|create.*agents\.md|update.*contributing|update.*context.?files'
SKILL_TIERS[md-docs]=3

SKILL_PATTERNS[refine-prompt]='refine.{0,15}prompt|improve.{0,15}prompt|promptify|optimize.{0,15}prompt|rewrite.{0,15}prompt|enhance.{0,15}prompt|sharpen.{0,15}instruction'
SKILL_TIERS[refine-prompt]=3

SKILL_PATTERNS[meta-prompting]='/think|/verify|/adversarial|argue.?against|what.?could.?break|deep.?review|meta.?prompt'
SKILL_TIERS[meta-prompting]=3

SKILL_PATTERNS[reflect]='/reflect|session.?review|retrospective|lessons.?learned|what.?went.?wrong'
SKILL_TIERS[reflect]=3

SKILL_PATTERNS[compound-docs]='document.*(solution|problem)|capture.*(knowledge|solved)|compound.*(doc|knowledge)'
SKILL_TIERS[compound-docs]=3

SKILL_PATTERNS[document-review]='refine.*(brainstorm|plan)|review.*(document|brainstorm|plan)'
SKILL_TIERS[document-review]=3

SKILL_PATTERNS[file-todos]='todo.?directory|manage.?todo|file.?based.?todo'
SKILL_TIERS[file-todos]=3

SKILL_PATTERNS[orchestrating-swarms]='multi.?agent|swarm|parallel.*(agent|task)|divide.?and.?conquer'
SKILL_TIERS[orchestrating-swarms]=3

SKILL_PATTERNS[git-worktree]='worktree|parallel.?development'
SKILL_TIERS[git-worktree]=3

SKILL_PATTERNS[resolve-pr-parallel]='resolve.*(thread|comment|pr)|batch.?resolve'
SKILL_TIERS[resolve-pr-parallel]=3


# Total skills: 30
