#!/usr/bin/env bash
# AUTO-GENERATED by scripts/generate-skill-hooks.sh — do not edit manually
# Generated: 2026-02-22T00:00:00Z
#
# To regenerate from SKILL.md frontmatter:
#   bash scripts/generate-skill-hooks.sh
# Then hand-tune the regex patterns as needed.

declare -A SKILL_PATTERNS
declare -A SKILL_TIERS

# --- Tier 1: Methodology (process/approach skills) ---

SKILL_PATTERNS[ia-planning]='plan.*(feature|task|sprint|this|implement|approach|phase|change|refactor|migration)|break.?down.*(feature|task)|implementation.?plan|(create|make|need|start|write|draft|let.?s).*plan|vertical.?slice'
SKILL_TIERS[ia-planning]=1

SKILL_PATTERNS[ia-debugging]='debug(?:ging)?.{0,30}(error|bug|fail|crash|issue|broken|problem|trace|stack|regression)|fix\s+(?:the\s+|this\s+)?bug|why.*(fail|broken|crash|error)|crash(es|ed|ing)|troubleshoot|stack.?trace|broken.?test|test.*broken|flaky.?test|regression.?(test|bug|fix)|unexpected.?behav'
SKILL_TIERS[ia-debugging]=1

SKILL_PATTERNS[ia-code-review]='review.*(code|\bprs?\b|diff|merge)|code.?review|audit.*code|critiqu'
SKILL_TIERS[ia-code-review]=1

SKILL_PATTERNS[ia-simplifying-code]='simplif\w*\s+(\w+\s+)?code|clean.?up.*code|polish.*code|\brefactor\b|declutter|reduce.?complexity|remove.*(dead.?code|ai.?slop)|improve.?readability'
SKILL_TIERS[ia-simplifying-code]=1

SKILL_PATTERNS[ia-brainstorming]='brainstorm|help.?me.?think|what.?should.?we.?build|explore.{0,40}(approach|idea|option|feature)|compare.{0,30}approach|clarify.{0,30}(requirement|ambigu)|vague.{0,30}(idea|feature|requirement)'
SKILL_TIERS[ia-brainstorming]=1

SKILL_PATTERNS[ia-verification-before-completion]='verif\w*\s.{0,20}(complet|pass|success)|completion.?claim|fresh.?evidence|verify.?before.{0,15}(commit|push|pr|merge|complet)|mark.{0,15}(done|complet)|ready.?to.?merge|claim.{0,30}(fixed|done|complete)'
SKILL_TIERS[ia-verification-before-completion]=1

SKILL_PATTERNS[ia-receiving-code-review]='reviewer.{0,20}(said|suggest|comment|flag|asked)|pr.?comment|mr.?comment|address.{0,30}(review|feedback)|implement.*(suggestion|feedback)|push.?back.*review|respond.*(review|feedback)'
SKILL_TIERS[ia-receiving-code-review]=1

SKILL_PATTERNS[ia-writing-tests]='writ.{0,25}(test|spec)|add.?test|test.?quality|test.?anti.?pattern|mock.*(bad|wrong|instead)|test.?discipline'
SKILL_TIERS[ia-writing-tests]=1


# --- Tier 2: Domain/Language (language/framework-specific) ---

SKILL_PATTERNS[ia-php-laravel]='laravel|eloquent|\bblade\b|\bartisan\b|phpunit|phpstan|composer\.(json|lock)|\bphp\b.{0,20}(controller|model|service|middleware|migration|queue|job|route|facade|factory|seeder)|feature.?test.*\.php|unit.?test.*\.php|test.*(controller|model|service|action|job|command|endpoint).*\.php'
SKILL_TIERS[ia-php-laravel]=2

SKILL_PATTERNS[ia-react-frontend]='react.{0,15}(component|hook|state|context|render|jsx|tsx|router)|next\.?js|react.*test|\bjsx\b|\btsx\b|\bhook[s]?\b.*component|vitest|component.?test|hook.?test|\brtl\b|testing.?library|snapshot.?test'
SKILL_TIERS[ia-react-frontend]=2

SKILL_PATTERNS[ia-nodejs-backend]='\bexpress\b.*(server|endpoint|route|api)|\bfastify\b|node\.?js.*(backend|server|api)|server.?side.?typescript'
SKILL_TIERS[ia-nodejs-backend]=2

SKILL_PATTERNS[ia-python-services]='\bfastapi\b|python.*(cli|service|backend|api)|async.*python|\bruff\b'
SKILL_TIERS[ia-python-services]=2

SKILL_PATTERNS[ia-rust-systems]='\brust\b.{0,30}(cli|service|binary|crate|workspace|backend|api|server|handler|async|tokio|axum|code|project|module)|async\s+rust|\bcargo\b.{0,20}(build|test|clippy|nextest|workspace|toml|deny)|\bclippy\b|\btokio\b|\baxum\b|\bclap\b.*(derive|parser|subcommand)|\bthiserror\b|\banyhow\b|cargo\.toml|\brustfmt\b|cargo-nextest|rust-toolchain|JoinSet|\bserde\b.*rust|\.rs\b.*(test|module|crate)'
SKILL_TIERS[ia-rust-systems]=2

SKILL_PATTERNS[ia-postgresql]='postgres(ql)?|\bpgbouncer\b|jsonb|row.?level.?security|\brls\b.{0,20}(policy|tenant|postgres|table)|\bcte[s]?\b.{0,30}(query|recurs|select|report)|window.?function|explain.?analyze|partition.{0,40}(range|list|hash|\bby\b)|\bupsert\b|tsvector|pg_stat_|pg_class'
SKILL_TIERS[ia-postgresql]=2

SKILL_PATTERNS[ia-terraform]='terraform|opentofu|\biac\b|infrastructure.?as.?code|\bhcl\b|tfvars|tftest'
SKILL_TIERS[ia-terraform]=2

SKILL_PATTERNS[ia-linux-bash-scripting]='bash.?script|shell.?script|linux.?automation|system.?script|cron.?job|deployment.?script'
SKILL_TIERS[ia-linux-bash-scripting]=2

SKILL_PATTERNS[ia-pinescript]='pine.?script|pinescript|tradingview.{0,30}(pine|indicator|strategy|chart|script)|\bindicator\b.{0,20}(pine|trading.?view)|\bstrategy\b.{0,20}(pine|trading.?view)|\.pine\b'
SKILL_TIERS[ia-pinescript]=2

SKILL_PATTERNS[ia-frontend-design]='frontend.*(design|interface)|ui.*(design|build|create)|(build|design).{0,30}(web.?component|web.?page|landing.?page|dashboard)|design.{0,20}too.?generic|ai.?generated.*(design|look)|color.?palette|visual.?identity'
SKILL_TIERS[ia-frontend-design]=2

SKILL_PATTERNS[ia-tailwind-css]='tailwind|@theme.*token|@utility.*css|tailwind.?variant|class.?variance|\bcva\b|\btv\(\b|utility.?class.*css|style.{0,30}utility.?class|dark.?mode.*css'
SKILL_TIERS[ia-tailwind-css]=2

SKILL_PATTERNS[ia-agent-native-architecture]='autonomous.?agent|mcp.?(tool|server)|self.?modif|agent.?(native|loop|hook)|prompt.?native|pretooluse|posttooluse'
SKILL_TIERS[ia-agent-native-architecture]=2

# --- Tier 3: Supporting/Workflow ---

SKILL_PATTERNS[ia-writing]='\brewrite\b|humanize|improve.*text|fix.*(tone|wording)|proofread|remove.*ai.?(language|tell|slop)|ai.?(writing|text).?tell|\bpr.?description\b|write.*(pull.?request|\bplan\b)'
SKILL_TIERS[ia-writing]=3

SKILL_PATTERNS[ia-md-docs]='update.*readme|update.*agents|init.*agents|create.*agents\.md|update.*contributing|update.*context.?files|claude\.md'
SKILL_TIERS[ia-md-docs]=3

SKILL_PATTERNS[ia-refine-prompt]='refine.{0,15}prompt|improve.{0,15}prompt|promptify|optimize.{0,15}prompt|rewrite.{0,15}prompt|enhance.{0,15}prompt|sharpen.{0,15}instruction|prompt.?engineer|tight.{0,10}system.?prompt'
SKILL_TIERS[ia-refine-prompt]=3

SKILL_PATTERNS[ia-meta-prompting]='/think|/verify|/adversarial|argue.?against|what.?could.?break|deep.?review|meta.?prompt'
SKILL_TIERS[ia-meta-prompting]=3

SKILL_PATTERNS[ia-reflect]='/reflect|session.?review|retrospective|lessons.?learned|what.?went.?wrong'
SKILL_TIERS[ia-reflect]=3

SKILL_PATTERNS[ia-compound-docs]='document.{0,40}(solution|problem|workaround)|capture.{0,40}(knowledge|solved|solution|debug)|compound.{0,30}(doc|knowledge)|post.?mortem'
SKILL_TIERS[ia-compound-docs]=3

SKILL_PATTERNS[ia-document-review]='(refine|polish|review|audit).{0,40}(brainstorm|plan|document|adr|spec)'
SKILL_TIERS[ia-document-review]=3

SKILL_PATTERNS[ia-file-todos]='todo.?directory|manage.?todo|file.?based.?todo'
SKILL_TIERS[ia-file-todos]=3

SKILL_PATTERNS[ia-orchestrating-swarms]='multi.?agent|swarm|parallel.*(agent|task)|divide.?and.?conquer'
SKILL_TIERS[ia-orchestrating-swarms]=3

SKILL_PATTERNS[ia-git-worktree]='worktree|parallel.?development'
SKILL_TIERS[ia-git-worktree]=3


# --- Project-type constraints (Tier 2 domain skills only) ---
# Skills listed here are suppressed when the detected project type doesn't match.
# Skills NOT listed pass unconditionally (tier 1 methodology, tier 3 workflow,
# and cross-stack domain skills like postgresql, linux-bash-scripting).
declare -A SKILL_PROJECT_TYPES

SKILL_PROJECT_TYPES[ia-php-laravel]="php"
SKILL_PROJECT_TYPES[ia-react-frontend]="js"
SKILL_PROJECT_TYPES[ia-nodejs-backend]="js"
SKILL_PROJECT_TYPES[ia-python-services]="python"
SKILL_PROJECT_TYPES[ia-terraform]="terraform"
SKILL_PROJECT_TYPES[ia-tailwind-css]="js"
SKILL_PROJECT_TYPES[ia-frontend-design]="js"

# --- Maintenance-context suppression ---
# Skills listed here fire on any prompt mentioning their name (e.g., "the brainstorming
# skill" or "skills/ia-writing-tests/SKILL.md"), which causes high false-positive rates
# during plugin-maintenance tasks (/sync-from-repos, /audit-plugin, distiller runs).
# These skills are suppressed when the prompt is recognized as plugin-maintenance context.
# Evidence: 2026-04-24 audit — brainstorming 85%, writing-tests 100%, planning 100% of
# negative-signal sessions were plugin-maintenance prompts where skill names appeared as
# references rather than user requests.
declare -A SKILL_MAINT_SUPPRESS
SKILL_MAINT_SUPPRESS[ia-brainstorming]=1
SKILL_MAINT_SUPPRESS[ia-writing-tests]=1
SKILL_MAINT_SUPPRESS[ia-planning]=1
# Added 2026-04-27 from analyze-outcomes anomalies (sync run):
# all five fire on plugin-maintenance prompts (audit/sync/release commands name them as references).
SKILL_MAINT_SUPPRESS[ia-verification-before-completion]=1  # 24 sessions, 45.8% neg, +19pp -- "verification" appears in /audit-plugin, /release pre-commit gates
SKILL_MAINT_SUPPRESS[ia-postgresql]=1                       # 10 sessions, 70% neg, +52pp -- "postgresql" mentioned in distiller/audit prompts
SKILL_MAINT_SUPPRESS[ia-react-frontend]=1                   # 6 sessions, 33% neg, +24pp -- skill name still appears in plugin-doc/audit prompts; the `js` project-type guard at line 117 doesn't suppress those references, so MAINT backstops misfires
SKILL_MAINT_SUPPRESS[ia-writing]=1                          # 10 sessions, 20% neg, +12pp -- fires on plugin-doc work
# Added 2026-04-29 from analyze-outcomes anomalies (sync run):
SKILL_MAINT_SUPPRESS[ia-compound-docs]=1                    # 11 sessions, 36.4% neg, +11pp -- "compound" mentioned in /sync-from-repos and /audit-plugin
SKILL_MAINT_SUPPRESS[ia-terraform]=1                        # 7 sessions, 28.6% neg, +10pp -- plugin doesn't use terraform; misfire on audit/sync prompts
SKILL_MAINT_SUPPRESS[ia-python-services]=1                  # 14 sessions, 21.4% neg, +10pp -- fires on distiller.py work in plugin maintenance
# Added 2026-05-02 from diagnose-negatives ia-debugging (post-rename signal verified against pre-rename data):
SKILL_MAINT_SUPPRESS[ia-debugging]=1                        # 4/4 negative cases were plugin-maintenance tasks (auditing, skill restructuring, repo scanning) misfiring as debugging; analyze-outcomes 36% neg on -home-ilia-ai-php

# Total skills: 30
